### ISSUE TITLE
Endpoint to retrieve information from an entity

### ISSUE THREAD

**Issue by sofiaritz** [marcua/ayb#214]
In order to show things like existing databases and to verify that the credentials of a given user are correct, an endpoint to retrieve the information attached to an entity is required.

This endpoint would look something like this:
```bash
$ curl -w "\n" -X GET http://<instance>/v1/entity/sofiaritz -H "authorization: Bearer <valid_token>"

{"entity": "sofiaritz", "databases": ["test.sqlite", "project1.sqlite"]}

$ curl -w "\n" -X GET http://<instance>/v1/entity/sofiaritz -H "authorization: Bearer <invalid_token>"

{"message":"Invalid API token"}
```

**Comment by sofiaritz** [comment]
Implemented here: https://github.com/sofiaritz/ayb/tree/entity-info
I can create a PR if desired

**Comment by marcua** [comment]
Amazing @sofiaritz! This is great! Thank you so much!

Since you're actively working on this issue, I've added it to the middle column of the [project board](https://github.com/marcua/ayb/projects/1)

I have some tiny comments on avoiding exposing internal IDs and end-to-end testing, as well as a question on CORS/using the API from the browser (that I'll ask on #213), but I'm so impressed that you quickly implemented the changes you needed. When you submit the PR, I'm curious how you'd like to collaborate --- do you prefer comments you'll iterate on, or for me to iterate on the initial code you implemented? I'm happy to work in the most convenient way for you.

Thank you again! I'm so excited!

**Comment by sofiaritz** [comment]
> do you prefer comments you'll iterate on, or for me to iterate on the initial code you implemented?

Once the PR is submitted usually comments and change suggestions are best. If you find that the changes have some structural or design problems, I have no problem with you iterating on the submitted code. :)
I'll also ask for help if I need it at some point :p

> I have some tiny comments on avoiding exposing internal IDs and end-to-end testing, as well as a question on CORS/using the API from the browser

I'll reply to those in the linked issue. :)
